apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: init-project-
spec:
  pipelineRef:
    name: init-project-
  taskRunTemplate:
    serviceAccountName: pipeline
  workspaces:
    - name: src
      volumeClaimTemplate:
        metadata:
          creationTimestamp: null
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
          volumeMode: Filesystem
    - name: auth
      secret:
        secretName: -git-secret
    - name: additional-resources
      configMap:
        name: additional-resources-         
    - name: mvn-settings
      emptyDir: {}               
   
      