apiVersion: keycloak.org/v1alpha1
kind: KeycloakRealm
metadata:
  name: devjoy
spec:
  instanceSelector:
    matchLabels:
      app: sso
  realm:
    displayName: Devjoy
    enabled: true
    id: devjoy
    realm: devjoy
    identityProviders:
      - alias: "devjoy-ocp"
        providerId: "openshift-v4"
        enabled: true
        updateProfileFirstLoginMode: "on"
        trustEmail: false
        storeToken: false
        addReadTokenRoleOnCreate: false
        authenticateByDefault: false
        linkOnly: false
        firstBrokerLoginFlowAlias: "first broker login"
        config:
          syncMode: "IMPORT"
          baseUrl: "https://api.ocp4.stormshift.coe.muc.redhat.com:6443"
          clientSecret: "test"
          clientId: "example-11-client"
          useJwksUrl: "true"