apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: devjoy
  namespace: openshift-marketplace
spec:
  sourceType: grpc
  image: quay.io/devjoy/devjoy-operator-catalog:latest
  description:  Operator for Gitea
  publisher: devjoy.io
