apiVersion: v1
kind: Service
metadata:
  name: postgresql-
spec:
  ports:
  - name: postgresql
    port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    name: 
  sessionAffinity: None
  type: ClusterIP