apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: gitea-operator
  namespace: openshift-operators
spec:
  channel: stable
  installPlanApproval: Manual
  name: gitea-operator
  source: redhat-gpte-gitea
  sourceNamespace: openshift-marketplace
  startingCSV: gitea-operator.v1.3.0  