apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: redhat-gpte-gitea
  namespace: openshift-marketplace
spec:
  displayName: Red Hat GPTE (Gitea)
  image: 'quay.io/gpte-devops-automation/gitea-catalog:latest'
  publisher: Red Hat GPTE
  sourceType: grpc