FROM registry.access.redhat.com/ubi9/openjdk-17
RUN rm -rf .jbang \ 
  && curl -Ls https://sh.jbang.dev | bash -s - trust add https://repo1.maven.org/maven2/io/quarkus/quarkus-cli/ \
  && curl -Ls https://sh.jbang.dev | bash -s - app install --fresh --force quarkus@quarkusio
ENV PATH={$PATH}:/home/default/.jbang/bin
RUN quarkus --version --refresh
