FROM registry.access.redhat.com/ubi9/openjdk-17
#RUN curl -Ls "https://github.com/jbangdev/jbang/releases/download/v0.101.0/jbang-0.101.0.zip" --output jbang-0.101.0.zip && \
#    unzip jbang-0.101.0.zip && \
#    rm jbang-0.101.0.zip && \
#    chmod +x jbang-0.101.0/bin/jbang
#ENV PATH="${PATH}:/jbang-0.101.0/bin"
RUN curl -Ls https://sh.jbang.dev | bash -s - trust add https://repo1.maven.org/maven2/io/quarkus/quarkus-cli/
RUN curl -Ls https://sh.jbang.dev | bash -s - app install --fresh --force quarkus@quarkusio
RUN ls -la .jbang/bin 
ENV PATH={$PATH}:/home/default/.jbang/bin
